---
language: python
python: "2.7"
sudo: required
dist: trusty

# before_install:
  # - "echo OK"

install:
  - "pip install ansible"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"


script:
  # Check
  - >
    ansible-playbook tests/test.yml -Di tests/inventory -C

  # Deploy
  - >
    ansible-playbook tests/test.yml -Di tests/inventory

  # Idempotency check
  - >
    ansible-playbook tests/test.yml -Di tests/inventory
    | grep -q 'changed=0.*failed=0'

